let btnExp=document.querySelector(".title .btnExp"),hadith=document.querySelector(".hadith");btnExp.addEventListener("click",()=>{hadith.scrollIntoView({behavior:"smooth"})});let fixedDiv=document.querySelector(".header");window.addEventListener("scroll",()=>{window.scrollY>100?fixedDiv.classList.add("active"):fixedDiv.classList.remove("active")});let newbtn=document.querySelector(".btn3");window.onscroll=function(){window.scrollY>=200?newbtn.style.display="block":newbtn.style.display="none"},newbtn.onclick=function(){window.scrollTo({top:0,left:0,behavior:"smooth"})};let hadithDiv=document.querySelector(".hadithcontainer"),next=document.querySelector(".buttons .next"),prev=document.querySelector(".buttons .pre"),numbers=document.querySelector(".buttons .number"),hindex=0;function hadithchange(){fetch("https://api.hadith.gading.dev/books/muslim?range=1-80").then(e=>e.json()).then(e=>{let t=e.data.hadiths;function n(){hadithDiv.innerText=t[hindex].arab,numbers.innerText=`${hindex+1} - 80 `}n(),next.addEventListener("click",()=>{hindex<=80&&hindex++,n()}),prev.addEventListener("click",()=>{hindex>0&&hindex--,n()})})}hadithchange();let sections=document.querySelectorAll("section"),links=document.querySelectorAll(".header ul li");links.forEach(e=>{e.addEventListener("click",()=>{document.querySelector(".header ul li.active").classList.remove("active"),e.classList.add("active");let t=e.dataset.filter;sections.forEach(e=>{e.classList.contains(t)&&e.scrollIntoView({behavior:"smooth"})})})});let suarCountainer=document.querySelector(".sorahContianer");function getsorah(){fetch("https://api.alquran.cloud/v1/meta").then(e=>e.json()).then(e=>{let t=e.data.surahs.references;suarCountainer.innerHTML="";for(let n=0;n<t.length;n++)suarCountainer.innerHTML+=`
      <div class="sorah">
        <p> ${t[n].name}</p>
        <p>${t[n].englishName}</p>
      </div>
      `;let i=document.querySelectorAll(".sorah"),l=document.querySelector(".popup"),r=document.querySelector(".ayatcontainer");i.forEach((e,t)=>{e.addEventListener("click",()=>{fetch(`https://api.alquran.cloud/v1/surah/${t+1}`).then(e=>e.json()).then(e=>{r.innerHTML="";e.data.ayahs.forEach(e=>{l.classList.add("active"),r.innerHTML+=`
                <p class="ayatQ">${e.number} - ${e.text}</p>
                `})})})})});let e=document.querySelector(".closepoup"),t=document.querySelector(".popup");e.addEventListener("click",()=>{t.classList.remove("active")})}getsorah();let card=document.querySelector(".salahcontainer .card"),containerr=document.querySelector(".salahcontainer");function getTimee(){fetch("https://api.aladhan.com/v1/timingsByCity?city=cairo&country=egypt&method=8").then(e=>e.json()).then(e=>{let t=e.data.timings;for(let n in containerr.innerHTML="",t)containerr.innerHTML+=`
        <div class="card">
        <div class="time">
            ${n}
        </div>
        <div class="time2">
            ${t[n]}
        </div>
    </div>`})}getTimee();let elee=document.querySelector(".scroller"),height=document.documentElement.scrollHeight-document.documentElement.clientHeight;window.addEventListener("scroll",e=>{let t=document.documentElement.scrollTop;elee.style.width=`${t/height*100}%`});let active=document.querySelector(".container .bars .barrs"),sidbar=document.querySelector(".header ul");active.addEventListener("click",()=>{sidbar.classList.toggle("active")});let mooon=document.querySelector(".container .bars .mooon"),mooon2=document.querySelector(".header ul li .mooon2"),body=document.querySelector("#dark");mooon.addEventListener("click",()=>{body.classList.toggle("darkmood")}),mooon2.addEventListener("click",()=>{body.classList.toggle("darkmood")});const accordionItemHeaders=document.querySelectorAll(".accordion-item-header");accordionItemHeaders.forEach(e=>{e.addEventListener("click",t=>{e.classList.toggle("active");let n=e.nextElementSibling;e.classList.contains("active")?n.style.maxHeight=` ${n.scrollHeight}px`:n.style.maxHeight=0})});let lec1=document.getElementById("lec1"),lec2=document.getElementById("lec2"),lec3=document.getElementById("lec3"),lec4=document.getElementById("lec4"),lec5=document.getElementById("lec5");lec1.addEventListener("click",()=>{setTimeout(()=>{window.open("https://youtu.be/CMO5XQtPb3A?si=Qew4K8exfAWnHAZ8")},1e3)}),lec2.addEventListener("click",()=>{setTimeout(()=>{window.open("https://youtu.be/ku9YOLTDppk?si=4ADmKAsy936-luQx")},1e3)}),lec3.addEventListener("click",()=>{setTimeout(()=>{window.open("https://youtube.com/shorts/YwXC57PWoyc?si=7aBOSpD3Hq94wfus")},1e3)}),lec4.addEventListener("click",()=>{setTimeout(()=>{window.open("https://youtu.be/25eit4-JcFM?si=oShHar6QqWBDyz1X")},1e3)}),lec5.addEventListener("click",()=>{setTimeout(()=>{window.open("https://youtube.com/shorts/t9Zr0DSxVhA?si=kLAlWfPmHGoeRf2z")},1e3)});